#pragma once

/*
 * Keep tracked defaults as placeholders only.
 * For local development, copy `src/app_config.local.example.h` to
 * `src/app_config_local.h`, fill in real values there, and keep that file
 * ignored by git.
 */
#if __has_include("app_config_local.h")
#include "app_config_local.h"
#endif

#ifndef APP_WIFI_SSID
#define APP_WIFI_SSID "CHANGE_ME"
#endif

#ifndef APP_WIFI_PASSWORD
#define APP_WIFI_PASSWORD "CHANGE_ME"
#endif

#ifndef APP_HTTPS_TEST_URL
#define APP_HTTPS_TEST_URL "https://www.baidu.com/"
#endif

#ifndef APP_HTTPS_TEST_BEFORE_PROTOCOL
#define APP_HTTPS_TEST_BEFORE_PROTOCOL 0
#endif

#ifndef APP_PROTOCOL_BASE_URL
#define APP_PROTOCOL_BASE_URL "https://CHANGE_ME"
#endif

#ifndef APP_PROTOCOL_GET_CONFIG_PATH
#define APP_PROTOCOL_GET_CONFIG_PATH "/get_config"
#endif

#ifndef APP_PROTOCOL_START_AGENT_PATH
#define APP_PROTOCOL_START_AGENT_PATH "/v2/startAgent"
#endif

#ifndef APP_PROTOCOL_STOP_AGENT_PATH
#define APP_PROTOCOL_STOP_AGENT_PATH "/v2/stopAgent"
#endif

#ifndef APP_PROTOCOL_DEVICE_ID
#define APP_PROTOCOL_DEVICE_ID "cardputer-whip"
#endif

#ifndef APP_AGORA_AREA_CODE
#define APP_AGORA_AREA_CODE 0xFFFFFFFFU
#endif

#define APP_AUDIO_CODEC_G711A 1
#define APP_AUDIO_CODEC_G722 2
#define APP_AUDIO_CODEC_OPUS 3

#ifndef APP_AUDIO_CODEC
#define APP_AUDIO_CODEC APP_AUDIO_CODEC_G722
#endif

#ifndef APP_AUDIO_SAMPLE_RATE
#if APP_AUDIO_CODEC == APP_AUDIO_CODEC_G711A
#define APP_AUDIO_SAMPLE_RATE 8000
#elif APP_AUDIO_CODEC == APP_AUDIO_CODEC_G722
#define APP_AUDIO_SAMPLE_RATE 16000
#else
#define APP_AUDIO_SAMPLE_RATE 48000
#endif
#endif

#ifndef APP_AUDIO_CHANNELS
#define APP_AUDIO_CHANNELS 1
#endif

#ifndef APP_AUDIO_FRAME_MS
#define APP_AUDIO_FRAME_MS 20
#endif

#ifndef APP_AUDIO_USE_I2S_MIC
#define APP_AUDIO_USE_I2S_MIC 0
#endif

#ifndef APP_AUDIO_I2S_PORT
#define APP_AUDIO_I2S_PORT I2S_NUM_0
#endif

#ifndef APP_AUDIO_I2S_MIC_DATA_GPIO
#define APP_AUDIO_I2S_MIC_DATA_GPIO GPIO_NUM_46
#endif

#ifndef APP_AUDIO_I2S_MIC_CLK_GPIO
#define APP_AUDIO_I2S_MIC_CLK_GPIO GPIO_NUM_43
#endif

#ifndef APP_AUDIO_I2S_MIC_BCK_GPIO
#define APP_AUDIO_I2S_MIC_BCK_GPIO GPIO_NUM_NC
#endif

#ifndef APP_AUDIO_I2S_USE_CARDPUTER_ADV
#define APP_AUDIO_I2S_USE_CARDPUTER_ADV 0
#endif

#ifndef APP_AUDIO_I2S_ADV_I2C_PORT
#define APP_AUDIO_I2S_ADV_I2C_PORT I2C_NUM_0
#endif

#ifndef APP_AUDIO_I2S_ADV_I2C_SDA_GPIO
#define APP_AUDIO_I2S_ADV_I2C_SDA_GPIO GPIO_NUM_9
#endif

#ifndef APP_AUDIO_I2S_ADV_I2C_SCL_GPIO
#define APP_AUDIO_I2S_ADV_I2C_SCL_GPIO GPIO_NUM_8
#endif

#define APP_AUDIO_I2S_PDM_FMT_PCM 1
#define APP_AUDIO_I2S_PDM_FMT_RAW 0

#ifndef APP_AUDIO_I2S_PDM_DATA_FMT
#define APP_AUDIO_I2S_PDM_DATA_FMT APP_AUDIO_I2S_PDM_FMT_PCM
#endif

#ifndef APP_AUDIO_I2S_PDM_CLK_INVERT
#define APP_AUDIO_I2S_PDM_CLK_INVERT 0
#endif

#ifndef APP_AUDIO_I2S_AUTO_TUNE
#define APP_AUDIO_I2S_AUTO_TUNE 1
#endif

#ifndef APP_AUDIO_I2S_ALLOW_RAW_TUNE
#define APP_AUDIO_I2S_ALLOW_RAW_TUNE 0
#endif

#ifndef APP_AUDIO_I2S_CAPTURE_RATE
#define APP_AUDIO_I2S_CAPTURE_RATE 16000
#endif

#ifndef APP_AUDIO_I2S_ADV_ADC_VOLUME_REG
#define APP_AUDIO_I2S_ADV_ADC_VOLUME_REG 0xE7
#endif

#ifndef APP_AUDIO_I2S_ADV_PGA_REG
#define APP_AUDIO_I2S_ADV_PGA_REG 0x1C
#endif

#ifndef APP_AUDIO_I2S_ADV_STARTUP_DELAY_MS
#define APP_AUDIO_I2S_ADV_STARTUP_DELAY_MS 50
#endif

#ifndef APP_AUDIO_I2S_ADV_CODEC_RESET_DELAY_MS
#define APP_AUDIO_I2S_ADV_CODEC_RESET_DELAY_MS 20
#endif

#ifndef APP_AUDIO_I2S_ADV_ADC_SETTLE_DELAY_MS
#define APP_AUDIO_I2S_ADV_ADC_SETTLE_DELAY_MS 250
#endif

#ifndef APP_AUDIO_I2S_ADV_POST_PLAYBACK_AUTOTUNE_SUPPRESS_MS
#define APP_AUDIO_I2S_ADV_POST_PLAYBACK_AUTOTUNE_SUPPRESS_MS 5000
#endif

#ifndef APP_AUDIO_I2S_ADV_RECOVERY_RETRY_ENABLE
#define APP_AUDIO_I2S_ADV_RECOVERY_RETRY_ENABLE 1
#endif

#ifndef APP_AUDIO_I2S_SPK_PORT
#define APP_AUDIO_I2S_SPK_PORT I2S_NUM_0
#endif

#ifndef APP_AUDIO_I2S_SPK_BCK_GPIO
#define APP_AUDIO_I2S_SPK_BCK_GPIO GPIO_NUM_41
#endif

#ifndef APP_AUDIO_I2S_SPK_WS_GPIO
#define APP_AUDIO_I2S_SPK_WS_GPIO GPIO_NUM_43
#endif

#ifndef APP_AUDIO_I2S_SPK_DOUT_GPIO
#define APP_AUDIO_I2S_SPK_DOUT_GPIO GPIO_NUM_42
#endif

#ifndef APP_AUDIO_I2S_ADV_DAC_VOLUME_REG
#define APP_AUDIO_I2S_ADV_DAC_VOLUME_REG 0xC0
#endif

#ifndef APP_AUDIO_I2S_GAIN_NUM
#define APP_AUDIO_I2S_GAIN_NUM 8
#endif

#ifndef APP_AUDIO_I2S_GAIN_DEN
#define APP_AUDIO_I2S_GAIN_DEN 1
#endif

#ifndef APP_AUDIO_I2S_OUTPUT_LIMIT
#define APP_AUDIO_I2S_OUTPUT_LIMIT 22000
#endif

#ifndef APP_AUDIO_I2S_SOFT_KNEE
#define APP_AUDIO_I2S_SOFT_KNEE 9000
#endif

#ifndef APP_AUDIO_I2S_PROFILE_ENABLE
#define APP_AUDIO_I2S_PROFILE_ENABLE 1
#endif

#ifndef APP_AUDIO_FAKE_TONE_HZ
#define APP_AUDIO_FAKE_TONE_HZ 440
#endif

#ifndef APP_AUDIO_FAKE_AMPLITUDE
#define APP_AUDIO_FAKE_AMPLITUDE 12000
#endif

#ifndef APP_AUDIO_ENABLE_PULL_PLAYBACK
#define APP_AUDIO_ENABLE_PULL_PLAYBACK 0
#endif

#ifndef APP_AUDIO_ENABLE_HALF_DUPLEX_GATING
#define APP_AUDIO_ENABLE_HALF_DUPLEX_GATING 1
#endif

#ifndef APP_AUDIO_REMOTE_TAIL_MS
#define APP_AUDIO_REMOTE_TAIL_MS 1200
#endif

#ifndef APP_AUDIO_MODE_MIN_HOLD_MS
#define APP_AUDIO_MODE_MIN_HOLD_MS 1200
#endif

#ifndef APP_AUDIO_PLAYBACK_REARM_COOLDOWN_MS
#define APP_AUDIO_PLAYBACK_REARM_COOLDOWN_MS 500
#endif

#ifndef APP_AUDIO_REMOTE_ACTIVE_AVG_ABS_THRESHOLD
#define APP_AUDIO_REMOTE_ACTIVE_AVG_ABS_THRESHOLD 16
#endif

#ifndef APP_AUDIO_REMOTE_ACTIVE_PEAK_THRESHOLD
#define APP_AUDIO_REMOTE_ACTIVE_PEAK_THRESHOLD 64
#endif

#ifndef APP_AUDIO_REMOTE_REARM_AVG_ABS_THRESHOLD
#define APP_AUDIO_REMOTE_REARM_AVG_ABS_THRESHOLD 900
#endif

#ifndef APP_AUDIO_REMOTE_REARM_PEAK_THRESHOLD
#define APP_AUDIO_REMOTE_REARM_PEAK_THRESHOLD 5000
#endif

#ifndef APP_AUDIO_I2S_ADV_RESTART_DELAY_MS
#define APP_AUDIO_I2S_ADV_RESTART_DELAY_MS 150
#endif

#ifndef APP_AUDIO_I2S_ADV_RESTART_FLUSH_READS
#define APP_AUDIO_I2S_ADV_RESTART_FLUSH_READS 4
#endif

#ifndef APP_AUDIO_PLAYBACK_RUN_SELF_TEST
#define APP_AUDIO_PLAYBACK_RUN_SELF_TEST 0
#endif

#ifndef APP_AUDIO_PLAYBACK_GAIN_NUM
#define APP_AUDIO_PLAYBACK_GAIN_NUM 8
#endif

#ifndef APP_AUDIO_PLAYBACK_GAIN_DEN
#define APP_AUDIO_PLAYBACK_GAIN_DEN 1
#endif

#ifndef APP_AUDIO_PLAYBACK_MAX_EFFECTIVE_GAIN_NUM
#define APP_AUDIO_PLAYBACK_MAX_EFFECTIVE_GAIN_NUM 8
#endif

#ifndef APP_AUDIO_PLAYBACK_MAX_EFFECTIVE_GAIN_DEN
#define APP_AUDIO_PLAYBACK_MAX_EFFECTIVE_GAIN_DEN 1
#endif

#ifndef APP_AUDIO_PLAYBACK_OUTPUT_LIMIT
#define APP_AUDIO_PLAYBACK_OUTPUT_LIMIT 22000
#endif

#ifndef APP_AUDIO_PLAYBACK_SOFT_KNEE
#define APP_AUDIO_PLAYBACK_SOFT_KNEE 9000
#endif

#ifndef APP_AUDIO_PLAYBACK_TEST_AMPLITUDE
#define APP_AUDIO_PLAYBACK_TEST_AMPLITUDE 20000
#endif

#ifndef APP_AGORA_AUTO_START
#define APP_AGORA_AUTO_START 1
#endif

#ifndef APP_AGORA_START_ON_KEYPRESS
#define APP_AGORA_START_ON_KEYPRESS 1
#endif

#ifndef APP_AGORA_START_KEY
#define APP_AGORA_START_KEY 'k'
#endif

#ifndef APP_AGORA_RENEW_BEFORE_EXPIRY_SEC
#define APP_AGORA_RENEW_BEFORE_EXPIRY_SEC 60
#endif

#ifndef APP_AGORA_PROTOCOL_OUTPUT_AUDIO_CODEC
#define APP_AGORA_PROTOCOL_OUTPUT_AUDIO_CODEC "g722"
#endif
